import { alpha, gruvboxDark as p } from "../palette.ts";
import type { ColorTheme } from "../types.ts";

/**
 * Zed Gruvbox Dark.
 *
 * Ported from Zed's `Gruvbox Dark` theme (`themes[0]` in
 * `assets/themes/gruvbox/gruvbox.json`). Zed's `style` keys have no VS Code
 * counterparts, so each group below notes which Zed token it stands in for:
 *
 *   background (#4c4642)         -> status bar, title bar
 *   surface.background (#3a3735) -> side bar, panels, tab bar, widgets
 *   toolbar.background (#282828) -> editor pane and active tab
 *   element.hover / .active      -> list and button states
 *
 * `border.variant` and `element.hover` share #494340 upstream, so `borderVariant`
 * covers both roles here.
 */
export const zedGruvboxDark: ColorTheme = {
  name: "Zed Gruvbox Dark",
  type: "dark",
  semanticHighlighting: true,

  colors: {
    // Base — Zed `text`, `text.muted`, `border`, `border.focused`
    foreground: p.text,
    descriptionForeground: p.textMuted,
    disabledForeground: p.textPlaceholder,
    errorForeground: p.deleted,
    focusBorder: p.borderFocused,
    "widget.border": p.border,
    "widget.shadow": alpha(p.editorBg, 0.4),
    "selection.background": alpha(p.brightBlue, 0.24),
    "icon.foreground": p.text,
    "textLink.foreground": p.brightBlue,
    "textLink.activeForeground": p.brightBlue,
    "textPreformat.foreground": p.brightCyan,
    "textBlockQuote.background": p.surface,
    "textBlockQuote.border": p.borderVariant,
    "textCodeBlock.background": p.surface,
    "textSeparator.foreground": p.borderVariant,
    "toolbar.hoverBackground": p.borderVariant,
    "toolbar.activeBackground": p.elementActive,
    "sash.hoverBorder": p.brightBlue,

    // Editor — Zed `editor.*`, `players[0]`, `search.*`
    "editor.background": p.editorBg,
    "editor.foreground": p.editorFg,
    "editorCursor.foreground": p.brightBlue,
    "editorLineNumber.foreground": p.lineNumber,
    "editorLineNumber.activeForeground": p.lineNumberActive,
    "editorLineNumber.dimmedForeground": p.lineNumberHover,
    "editor.lineHighlightBackground": alpha(p.surface, 0.75),
    "editor.rangeHighlightBackground": p.surface,
    "editor.symbolHighlightBackground": alpha(p.brightBlue, 0.4),
    "editor.selectionBackground": alpha(p.brightBlue, 0.24),
    "editor.inactiveSelectionBackground": alpha(p.brightBlue, 0.14),
    "editor.selectionHighlightBackground": alpha(p.brightBlue, 0.14),
    "editor.wordHighlightBackground": alpha(p.brightBlue, 0.1),
    "editor.wordHighlightStrongBackground": alpha(p.invisible, 0.4),
    "editor.findMatchBackground": alpha(p.searchMatch, 0.4),
    "editor.findMatchHighlightBackground": alpha(p.brightBlue, 0.4),
    "editor.findRangeHighlightBackground": alpha(p.surface, 0.75),
    "editor.hoverHighlightBackground": alpha(p.brightBlue, 0.1),
    "editor.linkedEditingBackground": alpha(p.brightBlue, 0.1),
    "editorWhitespace.foreground": p.invisible,
    "editorIndentGuide.background1": alpha(p.text, 0.05),
    "editorIndentGuide.activeBackground1": alpha(p.text, 0.1),
    "editorRuler.foreground": alpha(p.text, 0.05),
    "editorBracketMatch.background": alpha(p.brightBlue, 0.1),
    "editorBracketMatch.border": p.brightBlue,
    "editorBracketHighlight.foreground1": p.comment,
    "editorBracketHighlight.foreground2": p.brightBlue,
    "editorBracketHighlight.foreground3": p.brightCyan,
    "editorBracketHighlight.foreground4": p.brightMagenta,
    "editorBracketHighlight.foreground5": p.syntaxYellow,
    "editorBracketHighlight.foreground6": p.syntaxOrange,
    "editorBracketHighlight.unexpectedBracket.foreground": p.syntaxRed,
    "editorCodeLens.foreground": p.hint,
    "editorInlayHint.foreground": p.hint,
    "editorInlayHint.background": p.infoBg,
    "editorGhostText.foreground": p.predictive,
    "editorLightBulb.foreground": p.syntaxYellow,
    "editorLightBulbAutoFix.foreground": p.brightCyan,
    "editorUnnecessaryCode.opacity": alpha(p.editorBg, 0.6),

    // Editor gutter, overview ruler — Zed `editor.gutter.background`, `version_control.*`
    "editorGutter.background": p.editorBg,
    "editorGutter.addedBackground": p.added,
    "editorGutter.modifiedBackground": p.modified,
    "editorGutter.deletedBackground": p.deleted,
    "editorGutter.foldingControlForeground": p.textMuted,
    "editorOverviewRuler.border": p.trackBorder,
    "editorOverviewRuler.findMatchForeground": alpha(p.searchMatch, 0.4),
    "editorOverviewRuler.selectionHighlightForeground": alpha(p.brightBlue, 0.4),
    "editorOverviewRuler.wordHighlightForeground": alpha(p.invisible, 0.4),
    "editorOverviewRuler.addedForeground": p.added,
    "editorOverviewRuler.modifiedForeground": p.modified,
    "editorOverviewRuler.deletedForeground": p.deleted,
    "editorOverviewRuler.errorForeground": p.deleted,
    "editorOverviewRuler.warningForeground": p.modified,
    "editorOverviewRuler.infoForeground": p.brightBlue,
    "editorOverviewRuler.bracketMatchForeground": p.comment,

    // Diagnostics — Zed `error`, `warning`, `info`, `hint`
    "editorError.foreground": p.deleted,
    "editorWarning.foreground": p.modified,
    "editorInfo.foreground": p.brightBlue,
    "editorHint.foreground": p.hint,
    "problemsErrorIcon.foreground": p.deleted,
    "problemsWarningIcon.foreground": p.modified,
    "problemsInfoIcon.foreground": p.brightBlue,

    // Editor widgets — Zed `elevated_surface.background`
    "editorWidget.background": p.surface,
    "editorWidget.foreground": p.text,
    "editorWidget.border": p.border,
    "editorHoverWidget.background": p.surface,
    "editorHoverWidget.border": p.border,
    "editorSuggestWidget.background": p.surface,
    "editorSuggestWidget.border": p.border,
    "editorSuggestWidget.foreground": p.text,
    "editorSuggestWidget.highlightForeground": p.brightBlue,
    "editorSuggestWidget.selectedBackground": p.elementActive,
    "editorSuggestWidget.focusHighlightForeground": p.brightBlue,
    "editorMarkerNavigation.background": p.surface,
    "editorMarkerNavigationError.background": p.deleted,
    "editorMarkerNavigationWarning.background": p.modified,
    "editorMarkerNavigationInfo.background": p.brightBlue,
    "debugExceptionWidget.background": p.deletedBg,
    "debugExceptionWidget.border": p.deletedBorder,

    // Diff and merge — Zed `created`, `deleted`, `conflict`
    "diffEditor.insertedTextBackground": alpha(p.added, 0.1),
    "diffEditor.removedTextBackground": alpha(p.deleted, 0.1),
    "diffEditor.insertedLineBackground": alpha(p.added, 0.08),
    "diffEditor.removedLineBackground": alpha(p.deleted, 0.08),
    "diffEditor.diagonalFill": p.borderVariant,
    "diffEditor.border": p.borderVariant,
    "merge.currentHeaderBackground": p.addedBorder,
    "merge.currentContentBackground": p.addedBg,
    "merge.incomingHeaderBackground": p.borderFocused,
    "merge.incomingContentBackground": p.infoBg,
    "merge.commonHeaderBackground": alpha(p.brightBlack, 0.3),
    "merge.commonContentBackground": alpha(p.brightBlack, 0.15),
    "merge.border": p.modifiedBorder,
    "editorOverviewRuler.currentContentForeground": p.added,
    "editorOverviewRuler.incomingContentForeground": p.brightBlue,
    "editorOverviewRuler.commonContentForeground": p.brightBlack,

    // Peek view
    "peekView.border": p.brightBlue,
    "peekViewEditor.background": p.surface,
    "peekViewEditor.matchHighlightBackground": alpha(p.searchMatch, 0.4),
    "peekViewEditorGutter.background": p.surface,
    "peekViewResult.background": p.surface,
    "peekViewResult.foreground": p.text,
    "peekViewResult.lineForeground": p.textMuted,
    "peekViewResult.fileForeground": p.text,
    "peekViewResult.selectionBackground": p.elementActive,
    "peekViewResult.selectionForeground": p.text,
    "peekViewResult.matchHighlightBackground": alpha(p.searchMatch, 0.4),
    "peekViewTitle.background": p.surface,
    "peekViewTitleLabel.foreground": p.text,
    "peekViewTitleDescription.foreground": p.textMuted,

    // Title bar — Zed `title_bar.background`, `title_bar.inactive_background`
    "titleBar.activeBackground": p.bg,
    "titleBar.activeForeground": p.text,
    "titleBar.inactiveBackground": p.surface,
    "titleBar.inactiveForeground": p.textPlaceholder,
    "titleBar.border": p.borderVariant,

    // Status bar — Zed `status_bar.background`
    "statusBar.background": p.bg,
    "statusBar.foreground": p.textMuted,
    "statusBar.border": p.borderVariant,
    "statusBar.noFolderBackground": p.surface,
    "statusBar.noFolderForeground": p.textMuted,
    "statusBar.debuggingBackground": p.accentOrange,
    "statusBar.debuggingForeground": p.editorBg,
    "statusBar.focusBorder": p.brightBlue,
    "statusBarItem.hoverBackground": p.borderVariant,
    "statusBarItem.activeBackground": p.elementActive,
    "statusBarItem.remoteBackground": p.surface,
    "statusBarItem.remoteForeground": p.brightBlue,
    "statusBarItem.errorBackground": p.deletedBg,
    "statusBarItem.errorForeground": p.deleted,
    "statusBarItem.warningBackground": p.modifiedBg,
    "statusBarItem.warningForeground": p.modified,
    "statusBarItem.prominentBackground": p.elementActive,
    "statusBarItem.prominentForeground": p.text,

    // Activity bar — Zed `surface.background`, `icon.*`
    "activityBar.background": p.surface,
    "activityBar.foreground": p.text,
    "activityBar.inactiveForeground": p.textPlaceholder,
    "activityBar.border": p.borderVariant,
    "activityBar.activeBorder": p.brightBlue,
    "activityBar.activeBackground": p.borderVariant,
    "activityBarBadge.background": p.brightBlue,
    "activityBarBadge.foreground": p.editorBg,
    "activityBarTop.foreground": p.text,
    "activityBarTop.inactiveForeground": p.textPlaceholder,
    "activityBarTop.activeBorder": p.brightBlue,

    // Side bar — Zed `surface.background`
    "sideBar.background": p.surface,
    "sideBar.foreground": p.textMuted,
    "sideBar.border": p.borderVariant,
    "sideBar.dropBackground": alpha(p.textMuted, 0.5),
    "sideBarTitle.foreground": p.text,
    "sideBarSectionHeader.background": p.surface,
    "sideBarSectionHeader.foreground": p.text,
    "sideBarSectionHeader.border": p.borderVariant,

    // Tabs — Zed `tab_bar.background`, `tab.active_background`
    "editorGroupHeader.tabsBackground": p.surface,
    "editorGroupHeader.tabsBorder": p.borderVariant,
    "editorGroupHeader.noTabsBackground": p.surface,
    "editorGroup.border": p.borderVariant,
    "editorGroup.dropBackground": alpha(p.textMuted, 0.5),
    "editorGroup.emptyBackground": p.editorBg,
    "tab.activeBackground": p.editorBg,
    "tab.activeForeground": p.text,
    // Borderless active tab: both edges blend into the editor background
    "tab.activeBorder": p.editorBg,
    "tab.activeBorderTop": p.editorBg,
    "tab.inactiveBackground": p.surface,
    "tab.inactiveForeground": p.textPlaceholder,
    "tab.hoverBackground": p.borderVariant,
    "tab.hoverForeground": p.text,
    "tab.unfocusedActiveBackground": p.surface,
    "tab.unfocusedActiveForeground": p.textMuted,
    "tab.unfocusedInactiveForeground": p.textPlaceholder,
    "tab.border": p.borderVariant,
    "tab.lastPinnedBorder": p.border,
    "tab.activeModifiedBorder": p.modified,
    "tab.inactiveModifiedBorder": p.modifiedBorder,

    // Breadcrumbs — Zed `toolbar.background`
    "breadcrumb.background": p.editorBg,
    "breadcrumb.foreground": p.textMuted,
    "breadcrumb.focusForeground": p.text,
    "breadcrumb.activeSelectionForeground": p.brightBlue,
    "breadcrumbPicker.background": p.surface,
    // Line along the bottom of the `.title` container. In Cursor the file-path/AI
    // bar sits below `.title`, so this reads as a border under the tab row and
    // outranks `tab.activeBorder` on the active tab.
    "editorGroupHeader.border": p.borderVariant,

    // Lists and trees — Zed `element.hover`, `element.active`, `drop_target.background`
    "list.activeSelectionBackground": p.elementActive,
    "list.activeSelectionForeground": p.text,
    "list.activeSelectionIconForeground": p.text,
    "list.inactiveSelectionBackground": p.borderVariant,
    "list.inactiveSelectionForeground": p.textMuted,
    "list.hoverBackground": p.borderVariant,
    "list.hoverForeground": p.text,
    "list.focusBackground": p.elementActive,
    "list.focusForeground": p.text,
    "list.focusOutline": p.borderFocused,
    "list.highlightForeground": p.brightBlue,
    "list.focusHighlightForeground": p.brightBlue,
    "list.dropBackground": alpha(p.textMuted, 0.5),
    "list.errorForeground": p.deleted,
    "list.warningForeground": p.modified,
    "list.deemphasizedForeground": p.textPlaceholder,
    "list.invalidItemForeground": p.textPlaceholder,
    "listFilterWidget.background": p.surface,
    "listFilterWidget.outline": p.brightBlue,
    "listFilterWidget.noMatchesOutline": p.deleted,
    "tree.indentGuidesStroke": p.borderVariant,
    "tree.inactiveIndentGuidesStroke": p.borderDisabled,

    // Inputs, dropdowns, buttons, badges — Zed `element.*`, `text.placeholder`
    "input.background": p.surface,
    "input.foreground": p.text,
    "input.border": p.border,
    "input.placeholderForeground": p.textPlaceholder,
    "inputOption.activeBackground": p.elementActive,
    "inputOption.activeForeground": p.text,
    "inputOption.activeBorder": p.brightBlue,
    "inputValidation.errorBackground": p.deletedBg,
    "inputValidation.errorBorder": p.deletedBorder,
    "inputValidation.warningBackground": p.modifiedBg,
    "inputValidation.warningBorder": p.modifiedBorder,
    "inputValidation.infoBackground": p.infoBg,
    "inputValidation.infoBorder": p.borderFocused,
    "dropdown.background": p.surface,
    "dropdown.listBackground": p.surface,
    "dropdown.foreground": p.text,
    "dropdown.border": p.border,
    "button.background": p.elementActive,
    "button.foreground": p.text,
    "button.hoverBackground": p.borderVariant,
    "button.border": p.border,
    "button.secondaryBackground": p.surface,
    "button.secondaryForeground": p.textMuted,
    "button.secondaryHoverBackground": p.borderVariant,
    "checkbox.background": p.surface,
    "checkbox.foreground": p.text,
    "checkbox.border": p.border,
    "badge.background": p.brightBlue,
    "badge.foreground": p.editorBg,
    "progressBar.background": p.brightBlue,
    "keybindingLabel.background": p.surface,
    "keybindingLabel.foreground": p.text,
    "keybindingLabel.border": p.border,
    "keybindingLabel.bottomBorder": p.borderVariant,

    // Scrollbars and minimap — Zed `scrollbar.*`
    "scrollbar.shadow": alpha(p.editorBg, 0.4),
    "scrollbarSlider.background": alpha(p.comment, 0.3),
    "scrollbarSlider.hoverBackground": alpha(p.text, 0.3),
    "scrollbarSlider.activeBackground": alpha(p.brightBlue, 0.675),
    "minimap.background": p.editorBg,
    "minimap.selectionHighlight": alpha(p.brightBlue, 0.24),
    "minimap.findMatchHighlight": alpha(p.searchMatch, 0.4),
    "minimap.errorHighlight": p.deleted,
    "minimap.warningHighlight": p.modified,
    "minimapGutter.addedBackground": p.added,
    "minimapGutter.modifiedBackground": p.modified,
    "minimapGutter.deletedBackground": p.deleted,
    "minimapSlider.background": alpha(p.comment, 0.15),
    "minimapSlider.hoverBackground": alpha(p.text, 0.15),
    "minimapSlider.activeBackground": alpha(p.brightBlue, 0.3),

    // Panels and quick input — Zed `panel.background`, `panel.focused_border`
    "panel.background": p.surface,
    "panel.border": p.borderVariant,
    "panel.dropBorder": p.brightBlue,
    "panelTitle.activeForeground": p.text,
    "panelTitle.activeBorder": p.brightBlue,
    "panelTitle.inactiveForeground": p.textPlaceholder,
    "panelSection.border": p.borderVariant,
    "panelSectionHeader.background": p.surface,
    "panelSectionHeader.foreground": p.text,
    "quickInput.background": p.surface,
    "quickInput.foreground": p.text,
    "quickInputList.focusBackground": p.elementActive,
    "quickInputList.focusForeground": p.text,
    "quickInputList.focusIconForeground": p.text,
    "quickInputTitle.background": p.surface,
    "pickerGroup.border": p.borderVariant,
    "pickerGroup.foreground": p.brightBlue,
    "menu.background": p.surface,
    "menu.foreground": p.text,
    "menu.border": p.border,
    "menu.selectionBackground": p.elementActive,
    "menu.selectionForeground": p.text,
    "menu.separatorBackground": p.borderVariant,
    "menubar.selectionBackground": p.borderVariant,
    "menubar.selectionForeground": p.text,

    // Notifications and banners — Zed `error`, `warning`, `info`
    "notificationCenter.border": p.border,
    "notificationCenterHeader.background": p.surface,
    "notificationCenterHeader.foreground": p.text,
    "notifications.background": p.surface,
    "notifications.foreground": p.text,
    "notifications.border": p.borderVariant,
    "notificationToast.border": p.border,
    "notificationLink.foreground": p.brightBlue,
    "notificationsErrorIcon.foreground": p.deleted,
    "notificationsWarningIcon.foreground": p.modified,
    "notificationsInfoIcon.foreground": p.brightBlue,
    "banner.background": p.surface,
    "banner.foreground": p.text,
    "banner.iconForeground": p.brightBlue,

    // Terminal — Zed `terminal.*`
    "terminal.background": p.editorBg,
    "terminal.foreground": p.editorFg,
    "terminal.border": p.borderVariant,
    "terminal.selectionBackground": alpha(p.brightBlue, 0.24),
    "terminalCursor.foreground": p.brightBlue,
    "terminalCursor.background": p.editorBg,
    "terminal.ansiBlack": p.editorBg,
    "terminal.ansiBrightBlack": p.brightBlack,
    "terminal.ansiRed": p.red,
    "terminal.ansiBrightRed": p.brightRed,
    "terminal.ansiGreen": p.green,
    "terminal.ansiBrightGreen": p.brightGreen,
    "terminal.ansiYellow": p.yellow,
    "terminal.ansiBrightYellow": p.brightYellow,
    "terminal.ansiBlue": p.blue,
    "terminal.ansiBrightBlue": p.brightBlue,
    "terminal.ansiMagenta": p.magenta,
    "terminal.ansiBrightMagenta": p.brightMagenta,
    "terminal.ansiCyan": p.cyan,
    "terminal.ansiBrightCyan": p.brightCyan,
    "terminal.ansiWhite": p.comment,
    "terminal.ansiBrightWhite": p.text,
    "terminalCommandDecoration.defaultBackground": p.dimFg,
    "terminalCommandDecoration.successBackground": p.added,
    "terminalCommandDecoration.errorBackground": p.deleted,

    // Version control — Zed `version_control.*`, `conflict`, `ignored`
    "gitDecoration.addedResourceForeground": p.added,
    "gitDecoration.untrackedResourceForeground": p.added,
    "gitDecoration.modifiedResourceForeground": p.modified,
    "gitDecoration.stageModifiedResourceForeground": p.modified,
    "gitDecoration.deletedResourceForeground": p.deleted,
    "gitDecoration.stageDeletedResourceForeground": p.deleted,
    "gitDecoration.renamedResourceForeground": p.brightBlue,
    "gitDecoration.conflictingResourceForeground": p.modified,
    "gitDecoration.ignoredResourceForeground": p.textPlaceholder,
    "gitDecoration.submoduleResourceForeground": p.brightCyan,
    "scm.providerBorder": p.borderVariant,

    // Debug and testing — Zed `success`, `error`, `warning`, `predictive`
    "debugToolBar.background": p.surface,
    "debugToolBar.border": p.border,
    "debugIcon.breakpointForeground": p.deleted,
    "debugIcon.breakpointDisabledForeground": p.textPlaceholder,
    "debugIcon.startForeground": p.added,
    "debugIcon.pauseForeground": p.modified,
    "debugIcon.stopForeground": p.deleted,
    "debugIcon.continueForeground": p.added,
    "debugIcon.stepOverForeground": p.brightBlue,
    "debugIcon.stepIntoForeground": p.brightBlue,
    "debugIcon.stepOutForeground": p.brightBlue,
    "debugIcon.restartForeground": p.brightCyan,
    "debugConsoleInputIcon.foreground": p.brightBlue,
    "debugTokenExpression.name": p.brightBlue,
    "debugTokenExpression.value": p.editorFg,
    "debugTokenExpression.string": p.syntaxGreen,
    "debugTokenExpression.number": p.brightMagenta,
    "debugTokenExpression.boolean": p.brightMagenta,
    "debugTokenExpression.error": p.deleted,
    "testing.iconPassed": p.added,
    "testing.iconFailed": p.deleted,
    "testing.iconErrored": p.deleted,
    "testing.iconQueued": p.modified,
    "testing.iconSkipped": p.textPlaceholder,
    "testing.iconUnset": p.textPlaceholder,
    "testing.message.error.decorationForeground": p.deleted,
    "testing.message.info.decorationForeground": p.brightBlue,

    // Welcome and settings surfaces
    "welcomePage.background": p.editorBg,
    "welcomePage.progress.background": p.surface,
    "welcomePage.progress.foreground": p.brightBlue,
    "welcomePage.tileBackground": p.surface,
    "welcomePage.tileHoverBackground": p.borderVariant,
    "walkThrough.embeddedEditorBackground": p.editorBg,
    "settings.headerForeground": p.text,
    "settings.modifiedItemIndicator": p.modified,
    "settings.focusedRowBackground": p.borderVariant,
    "settings.rowHoverBackground": p.surface,
    "settings.dropdownBackground": p.surface,
    "settings.dropdownBorder": p.border,
    "settings.textInputBackground": p.surface,
    "settings.textInputBorder": p.border,
    "settings.numberInputBackground": p.surface,
    "settings.numberInputBorder": p.border,
    "settings.checkboxBackground": p.surface,
    "settings.checkboxBorder": p.border,
  },

  semanticTokenColors: {
    // Zed `variable`, `property`, `primary` (#ebdbb2)
    variable: p.editorFg,
    property: p.editorFg,
    // Zed `variable.parameter`, `variable.special`, `namespace`, `label` (#83a598)
    parameter: p.brightBlue,
    namespace: p.brightBlue,
    label: p.brightBlue,
    decorator: p.brightBlue,
    "variable.defaultLibrary": p.brightBlue,
    "*.static": p.brightBlue,
    // Zed `constant` / `type` / `selector` (#fabd2e)
    type: p.syntaxYellow,
    class: p.syntaxYellow,
    interface: p.syntaxYellow,
    struct: p.syntaxYellow,
    typeParameter: p.syntaxYellow,
    // No `variable.readonly` entry on purpose: TypeScript marks every `const`
    // binding readonly, so mapping it to `constant` yellow paints ordinary locals
    // (`const tierA = …`). Zed only captures SCREAMING_CASE as `@constant`, which
    // semantic tokens cannot express — so consts fall through to `variable`.
    // Zed `enum` (#fe7f18)
    enum: p.syntaxOrange,
    // Zed `boolean` / `number` (#d3869b)
    number: p.brightMagenta,
    boolean: p.brightMagenta,
    enumMember: p.brightMagenta,
    // Zed `function` (#b8bb25). Note: no `*.defaultLibrary` override — TypeScript
    // tags every `lib.*.d.ts` member with it (`preventDefault`, `map`, `push`, …),
    // which is far broader than Zed's `function.builtin` capture.
    function: p.syntaxGreen,
    method: p.syntaxGreen,
    // Zed `keyword` / `preproc` (#fb4833)
    keyword: p.syntaxRed,
    modifier: p.syntaxRed,
    macro: p.syntaxRed,
    // Zed `operator` (#8ec07c)
    operator: p.brightCyan,
    // Zed `string` (#b8bb25), `comment` (#a89984), `string.regex` (#fe7f18)
    string: p.syntaxGreen,
    regexp: p.syntaxOrange,
    comment: p.comment,
    "comment.documentation": p.docComment,
  },

  tokenColors: [
    {
      name: "Comment — Zed `comment`",
      scope: ["comment", "punctuation.definition.comment"],
      settings: { foreground: p.comment },
    },
    {
      name: "Doc comment — Zed `comment.doc`",
      scope: [
        "comment.block.documentation",
        "comment.line.documentation",
        "string.quoted.docstring",
        "keyword.other.documentation",
        "storage.type.class.jsdoc",
        "entity.name.type.instance.jsdoc",
      ],
      settings: { foreground: p.docComment },
    },
    {
      name: "String — Zed `string`",
      scope: ["string", "string.quoted", "string.template", "meta.string"],
      settings: { foreground: p.syntaxGreen },
    },
    {
      name: "String escape — Zed `string.escape`",
      scope: ["constant.character.escape", "constant.character.string.escape"],
      settings: { foreground: p.docComment },
    },
    {
      name: "Regex — Zed `string.regex`",
      scope: [
        "string.regexp",
        "constant.regexp",
        "keyword.control.anchor.regexp",
        "keyword.operator.quantifier.regexp",
        "string.regexp constant.character.escape",
      ],
      settings: { foreground: p.syntaxOrange },
    },
    {
      name: "Special string — Zed `string.special`",
      scope: ["string.unquoted", "string.other.link", "constant.other.reference"],
      settings: { foreground: p.brightMagenta },
    },
    {
      name: "Symbol — Zed `string.special.symbol`",
      scope: ["constant.other.symbol", "constant.other.key", "variable.other.constant.symbol"],
      settings: { foreground: p.brightCyan },
    },
    {
      name: "Number and boolean — Zed `number`, `boolean`",
      scope: [
        "constant.numeric",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
        "constant.language.nil",
        // JSON lumps true/false/null into a bare `constant.language.json`, which
        // would otherwise fall through to the yellow `constant.language` rule
        "constant.language.json",
      ],
      settings: { foreground: p.brightMagenta },
    },
    {
      name: "Constant — Zed `constant`",
      scope: [
        "constant.language",
        "support.constant",
        "variable.other.constant",
        "variable.other.enummember",
      ],
      settings: { foreground: p.syntaxYellow },
    },
    {
      name: "Enum and variant — Zed `enum`",
      scope: ["entity.name.enum", "entity.name.type.enum", "support.type.enum"],
      settings: { foreground: p.syntaxOrange },
    },
    {
      name: "Keyword, storage, preprocessor — Zed `keyword`, `preproc`",
      scope: [
        "keyword",
        "keyword.control",
        "storage",
        "storage.type",
        "storage.modifier",
        "keyword.other.unit",
        "meta.preprocessor",
        "keyword.control.directive",
        "entity.name.function.preprocessor",
      ],
      settings: { foreground: p.syntaxRed },
    },
    {
      name: "Operator — Zed `operator`",
      scope: [
        "keyword.operator",
        "punctuation.separator.operator",
        "storage.type.function.arrow",
      ],
      settings: { foreground: p.brightCyan },
    },
    {
      // Grammars scope `new`, `void` and `instanceof` under `keyword.operator`, but
      // Zed captures them as `@keyword` — keep them red alongside `return`, `if`, …
      name: "`new`, `void`, `instanceof` keywords — Zed `keyword`",
      scope: [
        "keyword.operator.new",
        "keyword.operator.expression.new",
        "keyword.operator.void",
        "keyword.operator.expression.void",
        "keyword.operator.instanceof",
        "keyword.operator.expression.instanceof",
      ],
      settings: { foreground: p.syntaxRed },
    },
    {
      name: "Function and method — Zed `function`",
      scope: [
        "entity.name.function",
        "meta.function-call entity.name.function",
        "support.function",
        "variable.function",
      ],
      settings: { foreground: p.syntaxGreen },
    },
    {
      name: "Builtin function — Zed `function.builtin`",
      scope: ["support.function.builtin", "support.function.magic", "keyword.other.special-method"],
      settings: { foreground: p.syntaxRed },
    },
    {
      name: "Type, class, selector — Zed `type`, `selector`",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.trait",
        "entity.name.struct",
        "support.type",
        "support.class",
        "storage.type.primitive",
        "entity.other.inherited-class",
        "entity.name.type.parameter",
        "entity.other.attribute-name.class",
        "entity.other.attribute-name.id",
      ],
      settings: { foreground: p.syntaxYellow },
    },
    {
      name: "Constructor, namespace, label — Zed `constructor`, `namespace`, `label`",
      scope: [
        "entity.name.function.constructor",
        "entity.name.namespace",
        "entity.name.module",
        "entity.name.scope-resolution",
        "entity.name.label",
        "meta.decorator",
        "entity.name.function.decorator",
        "punctuation.definition.decorator",
      ],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Parameter and special variable — Zed `variable.parameter`, `variable.special`",
      scope: [
        "variable.parameter",
        "variable.language",
        "variable.other.language",
        "entity.name.variable.parameter",
      ],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Variable and property — Zed `variable`, `property`, `primary`",
      scope: [
        "variable",
        "variable.other",
        "variable.other.readwrite",
        "meta.definition.variable",
        "variable.other.property",
        "variable.other.object.property",
        "support.type.property-name",
        "meta.object-literal.key",
      ],
      settings: { foreground: p.editorFg },
    },
    {
      name: "Attribute — Zed `attribute`",
      scope: ["entity.other.attribute-name", "meta.attribute"],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Tag — Zed `tag`",
      scope: ["entity.name.tag", "support.class.component"],
      settings: { foreground: p.brightCyan },
    },
    {
      name: "Pseudo selector — Zed `selector.pseudo`",
      scope: [
        "entity.other.attribute-name.pseudo-class",
        "entity.other.attribute-name.pseudo-element",
      ],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Punctuation — Zed `punctuation`",
      scope: ["punctuation", "punctuation.accessor", "punctuation.terminator"],
      settings: { foreground: p.punctuation },
    },
    {
      name: "Bracket — Zed `punctuation.bracket`",
      scope: [
        "meta.brace",
        "punctuation.section",
        "punctuation.definition.begin.bracket",
        "punctuation.definition.end.bracket",
        "punctuation.definition.parameters",
        "punctuation.definition.block",
      ],
      settings: { foreground: p.comment },
    },
    {
      name: "Delimiter and special punctuation — Zed `punctuation.delimiter`, `punctuation.special`",
      scope: [
        "punctuation.separator",
        "punctuation.definition.template-expression",
        "punctuation.section.embedded",
      ],
      settings: { foreground: p.delimiter },
    },
    {
      name: "List marker — Zed `punctuation.list_marker`",
      scope: ["punctuation.definition.list.begin", "markup.list punctuation.definition"],
      settings: { foreground: p.editorFg },
    },
    {
      name: "Markup punctuation — Zed `punctuation.markup`",
      scope: [
        "punctuation.definition.tag",
        "punctuation.definition.heading",
        "punctuation.definition.bold",
        "punctuation.definition.italic",
        "punctuation.definition.quote",
      ],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Embedded — Zed `embedded`",
      scope: ["meta.embedded", "source.embedded", "text.html source"],
      settings: { foreground: p.brightCyan },
    },
    {
      name: "Invalid",
      scope: ["invalid", "invalid.illegal"],
      settings: { foreground: p.syntaxRed, fontStyle: "underline" },
    },
    {
      name: "Markdown heading — Zed `title`",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: p.syntaxGreen, fontStyle: "bold" },
    },
    {
      name: "Markdown emphasis — Zed `emphasis`",
      scope: ["markup.italic"],
      settings: { foreground: p.brightBlue, fontStyle: "italic" },
    },
    {
      name: "Markdown strong — Zed `emphasis.strong`",
      scope: ["markup.bold"],
      settings: { foreground: p.brightBlue, fontStyle: "bold" },
    },
    {
      name: "Markdown link text — Zed `link_text`",
      scope: ["string.other.link.title", "markup.link", "constant.other.reference.link"],
      settings: { foreground: p.brightCyan, fontStyle: "italic" },
    },
    {
      name: "Markdown link uri — Zed `link_uri`",
      scope: ["markup.underline.link", "string.other.link.description"],
      settings: { foreground: p.brightMagenta },
    },
    {
      name: "Markdown literal — Zed `text.literal`",
      scope: ["markup.inline.raw", "markup.raw", "markup.fenced_code"],
      settings: { foreground: p.brightBlue },
    },
    {
      name: "Diff inserted — Zed `diff.plus`",
      scope: ["markup.inserted", "meta.diff.header.to-file"],
      settings: { foreground: p.brightGreen },
    },
    {
      name: "Diff deleted — Zed `diff.minus`",
      scope: ["markup.deleted", "meta.diff.header.from-file"],
      settings: { foreground: p.brightRed },
    },
    {
      name: "Diff changed",
      scope: ["markup.changed", "meta.diff.range"],
      settings: { foreground: p.modified },
    },
  ],
};
